MyStore.WebUI/Controllers/NavController.cs
using MyStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyStore.WebUI.Controllers
{
    
    public class NavController : Controller
    {  
        private IProductsRepository repository;
        public NavController(IProductsRepository _repo)
        {
            repository = _repo;
        }
        //
        // GET: /Nav/
        public PartialViewResult Menu(string CurrentCategory = null)
        {
            ViewBag.SelectedCategory = CurrentCategory; 
            var categories = repository.Products.Select(p => p.Category).Distinct().OrderBy(x=>x);
            return PartialView(categories);
        }
	}
}

MyStore.WebUI/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyStore.Domain.Abstract;
using MyStore.WebUI.Models;

namespace MyStore.WebUI.Controllers
{
   
    public class ProductsController : Controller
    {
        private IProductsRepository repository;
        public int PAGE_SIZE = 4;
        public ProductsController(IProductsRepository _repo)
        {
            repository = _repo;

        }
        //
        // GET: /Products/
        public ViewResult List(string category, int page =1 )
        {
            ProductsListViewModel productsListVM = new ProductsListViewModel
            {
                Products = repository.Products.Where(p=>category == null || p.Category==category).OrderBy(x => x.ProductID).
                Skip((page - 1) * PAGE_SIZE).
                Take(PAGE_SIZE),

                PagingInfo = new PageInfo
                {
                    CurrentPage = page ,
                    ItemsPerPage = PAGE_SIZE,
                    TotalItems = repository.Products.Where(p => category == null || p.Category == category).Count()
                    ,
                   
                },
                CurrentCategory = category

            };
            ViewBag.CurrentCategory = category; 
            return View(productsListVM);
        }
	}
}

MyStore.WebUI/Views/Shared/Menu.cshtml
@model IEnumerable<string>
<div style="margin-top:20px"></div>
@Html.ActionLink("Home", "List", "Products", null,
new { @class = "btn btn-block btn-default btn-lg" })
@foreach (var link in Model)
{
    @Html.RouteLink(link, new
{
    controller = "Products",
    action = "List",
    category = link,
    page = 1
}, new
{
    @class = "btn btn-block btn-default btn-lg"
    + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
})
}

MyStore.WebUI/Views/Shared/ProductSummary.cshtml
@model MyStore.Domain.Entities.Product

<div class="well">
    <h3>
        <strong>@Model.Name </strong>
       
        <span class="label label-primary pull-right" > @Model.Price.ToString("c")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {

        <div class="pull-right">

            @Html.HiddenFor(x => x.ProductID)
            @Html.Hidden("returnUrl",Request.Url.PathAndQuery)

            <input type="submit"  class="btn btn-success" value="Add To Cart" />

        </div>

    }
    <span class="lead">@Model.Description</span>
</div>

MyStore.WebUI/Views/Shared/Summary.cshtml
@model MyStore.Domain.Entities.Cart

<div class="navbar-right">
    @Html.ActionLink("Checkout", "Index", "Cart", new {returnUrl = Request.Url.PathAndQuery }, new  {@class="btn btn-default navbar-btn" })



</div>

<div class="navbar-right navbar-text">
    <b> Your Cart :</b>
    @Model.Lines.Sum(x=>x.Quantity) item(s),
    @Model.ComputeTotalValue().ToString("c") 


</div>

MyStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        @Html.Partial("_LoginPartial")
        @if (User.Identity.IsAuthenticated) { 
        @Html.Action("Summary","Cart")
        }
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MyStore", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "List", "Products")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>   
               
            </div>
        </div>
    </div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>

    }
    <div class="container body-content">
        <div class="row panel" >
            <div class="col-xs-3"> @Html.Action("Menu","Nav")</div>
            <div class="col-xs-8">@RenderBody()</div>
           
        </div>
       
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MyStore Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>